### ISSUE TITLE
trying to enable widgets and install my own widget implementations

### ISSUE THREAD

**Issue by AaronWatters** [rmotr/notebooks-help#4]
Hi.  I'm trying to add standard IPython widgets and also install my own widget implementations
and the installation steps are not working.

```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

ends with

<img width="1286" alt="screen shot 2019-01-10 at 2 30 46 pm" src="https://user-images.githubusercontent.com/13857252/50992604-a2a06e00-14e5-11e9-98dc-8904d393450e.png">

And I can't make a standard Button

<img width="938" alt="screen shot 2019-01-10 at 2 36 36 pm" src="https://user-images.githubusercontent.com/13857252/50992450-3a518c80-14e5-11e9-91c8-77a4763014d8.png">

I'm trying to follow instructions here, which work in other places:

https://github.com/AaronWatters/jp_proxy_widget

And ultimately I want this notebook to work as advertised:

https://github.com/AaronWatters/jp_doodle/blob/master/notebooks/workshop/Set%20up%20verification.ipynb

Thanks!

**Comment by AaronWatters** [comment]
According to https://github.com/benweet/stackedit/issues/1177 the exit code has to do with not enough memory.

**Comment by santiagobasulto** [comment]
Hello @AaronWatters ! Thanks for reaching out. Usually, a Python direct `Killed` message happens when you run out of memory. We're working on a way to create more powerful containers (more memory and CPU). I'll try installing widgets with that and if it works we can talk privately to enable extra resources for you!

**Comment by santiagobasulto** [comment]
@AaronWatters indeed, it's a problem of memory but also serving static files; we serve them from a CDN which doesn't include the js of the new extensions. Can you email me at santiago@rmotr.com and we'll see how to provide the extra resources.
