### ISSUE TITLE
My projects are gone!!

### ISSUE THREAD

**Issue by dclong** [rmotr/notebooks-help#7]
I had 3 projects in the dashboard but all of them are gone after I came back from a lunch!!! Cannot believe this happens the first time that I try to use it ...

**Comment by santiagobasulto** [comment]
Hey Ben! That is strange. We have encrypted backups of everything, so don't worry that you haven't lost anything.

Can you try logging out and in again?

**Comment by santiagobasulto** [comment]
I'm suggesting this because I'm checking the logs and I saw an "authentication error", maybe it logged you out but the token is still "half-active".

**Comment by dclong** [comment]
Just tried but still see no projects. I also tried in another browse that I never used to login before.

**Comment by santiagobasulto** [comment]
Can you please email me directly at santiago@rmotr.com? We'll figure this out because nothing is lost :)

**Comment by dclong** [comment]
@santiagobasulto Thank you, email sent!
